<?php

/**
 * BaseMedicijn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $Hoofdklasse
 * @property string $Generische_Naam
 * @property string $Specialiteit
 * @property string $Magistraat_Type
 * @property string $Type
 * @property integer $BNF_Percentage
 * @property integer $BNF_Getal
 * @property PatientMedicijn $PatientMedicijn
 * 
 * @method string          getHoofdklasse()     Returns the current record's "Hoofdklasse" value
 * @method string          getGenerischeNaam()  Returns the current record's "Generische_Naam" value
 * @method string          getSpecialiteit()    Returns the current record's "Specialiteit" value
 * @method string          getMagistraatType()  Returns the current record's "Magistraat_Type" value
 * @method string          getType()            Returns the current record's "Type" value
 * @method integer         getBNFPercentage()   Returns the current record's "BNF_Percentage" value
 * @method integer         getBNFGetal()        Returns the current record's "BNF_Getal" value
 * @method PatientMedicijn getPatientMedicijn() Returns the current record's "PatientMedicijn" value
 * @method Medicijn        setHoofdklasse()     Sets the current record's "Hoofdklasse" value
 * @method Medicijn        setGenerischeNaam()  Sets the current record's "Generische_Naam" value
 * @method Medicijn        setSpecialiteit()    Sets the current record's "Specialiteit" value
 * @method Medicijn        setMagistraatType()  Sets the current record's "Magistraat_Type" value
 * @method Medicijn        setType()            Sets the current record's "Type" value
 * @method Medicijn        setBNFPercentage()   Sets the current record's "BNF_Percentage" value
 * @method Medicijn        setBNFGetal()        Sets the current record's "BNF_Getal" value
 * @method Medicijn        setPatientMedicijn() Sets the current record's "PatientMedicijn" value
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedicijn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('medicijn');
        $this->hasColumn('Hoofdklasse', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('Generische_Naam', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('Specialiteit', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('Magistraat_Type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('Type', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('BNF_Percentage', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('BNF_Getal', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PatientMedicijn', array(
             'local' => 'id',
             'foreign' => 'Medicijn_id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}