<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IntEnzymGroup', 'doctrine');

/**
 * BaseIntEnzymGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $enzym_group_id
 * @property string $name
 * @property string $extra
 * @property Doctrine_Collection $IntInteraction
 * 
 * @method integer             getEnzymGroupId()   Returns the current record's "enzym_group_id" value
 * @method string              getName()           Returns the current record's "name" value
 * @method string              getExtra()          Returns the current record's "extra" value
 * @method Doctrine_Collection getIntInteraction() Returns the current record's "IntInteraction" collection
 * @method IntEnzymGroup       setEnzymGroupId()   Sets the current record's "enzym_group_id" value
 * @method IntEnzymGroup       setName()           Sets the current record's "name" value
 * @method IntEnzymGroup       setExtra()          Sets the current record's "extra" value
 * @method IntEnzymGroup       setIntInteraction() Sets the current record's "IntInteraction" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIntEnzymGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('int_enzym_group');
        $this->hasColumn('enzym_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
        $this->hasColumn('extra', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('IntInteraction', array(
             'local' => 'enzym_group_id',
             'foreign' => 'enzym_group_id'));
    }
}