<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MedKiVal', 'doctrine');

/**
 * BaseMedKiVal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $med_ki_val_id
 * @property string $value
 * @property integer $influence
 * @property string $tagval
 * @property Doctrine_Collection $MedFormBonding
 * 
 * @method integer             getMedKiValId()     Returns the current record's "med_ki_val_id" value
 * @method string              getValue()          Returns the current record's "value" value
 * @method integer             getInfluence()      Returns the current record's "influence" value
 * @method string              getTagval()         Returns the current record's "tagval" value
 * @method Doctrine_Collection getMedFormBonding() Returns the current record's "MedFormBonding" collection
 * @method MedKiVal            setMedKiValId()     Sets the current record's "med_ki_val_id" value
 * @method MedKiVal            setValue()          Sets the current record's "value" value
 * @method MedKiVal            setInfluence()      Sets the current record's "influence" value
 * @method MedKiVal            setTagval()         Sets the current record's "tagval" value
 * @method MedKiVal            setMedFormBonding() Sets the current record's "MedFormBonding" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedKiVal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('med_ki_val');
        $this->hasColumn('med_ki_val_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('value', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('influence', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tagval', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MedFormBonding', array(
             'local' => 'med_ki_val_id',
             'foreign' => 'med_ki_val_id'));
    }
}