<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdLog', 'doctrine');

/**
 * BaseAdLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ad_log
 * @property string $action
 * @property integer $ad_user_patient_id
 * @property timestamp $date
 * @property AdUserPatient $AdUserPatient
 * 
 * @method integer       getAdLog()              Returns the current record's "ad_log" value
 * @method string        getAction()             Returns the current record's "action" value
 * @method integer       getAdUserPatientId()    Returns the current record's "ad_user_patient_id" value
 * @method timestamp     getDate()               Returns the current record's "date" value
 * @method AdUserPatient getAdUserPatient()      Returns the current record's "AdUserPatient" value
 * @method AdLog         setAdLog()              Sets the current record's "ad_log" value
 * @method AdLog         setAction()             Sets the current record's "action" value
 * @method AdLog         setAdUserPatientId()    Sets the current record's "ad_user_patient_id" value
 * @method AdLog         setDate()               Sets the current record's "date" value
 * @method AdLog         setAdUserPatient()      Sets the current record's "AdUserPatient" value
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_log');
        $this->hasColumn('ad_log', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('action', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('ad_user_patient_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('date', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AdUserPatient', array(
             'local' => 'ad_user_patient_id',
             'foreign' => 'user_patient_id'));
    }
}