<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MedType', 'doctrine');

/**
 * BaseMedType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $med_type_id
 * @property integer $med_subtype1_id
 * @property integer $med_subtype2_id
 * @property MedSubtype1 $MedSubtype1
 * @property MedSubtype2 $MedSubtype2
 * @property Doctrine_Collection $MedBaseId
 * 
 * @method integer             getMedTypeId()       Returns the current record's "med_type_id" value
 * @method integer             getMedSubtype1Id()   Returns the current record's "med_subtype1_id" value
 * @method integer             getMedSubtype2Id()   Returns the current record's "med_subtype2_id" value
 * @method MedSubtype1         getMedSubtype1()     Returns the current record's "MedSubtype1" value
 * @method MedSubtype2         getMedSubtype2()     Returns the current record's "MedSubtype2" value
 * @method Doctrine_Collection getMedBaseId()       Returns the current record's "MedBaseId" collection
 * @method MedType             setMedTypeId()       Sets the current record's "med_type_id" value
 * @method MedType             setMedSubtype1Id()   Sets the current record's "med_subtype1_id" value
 * @method MedType             setMedSubtype2Id()   Sets the current record's "med_subtype2_id" value
 * @method MedType             setMedSubtype1()     Sets the current record's "MedSubtype1" value
 * @method MedType             setMedSubtype2()     Sets the current record's "MedSubtype2" value
 * @method MedType             setMedBaseId()       Sets the current record's "MedBaseId" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('med_type');
        $this->hasColumn('med_type_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('med_subtype1_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('med_subtype2_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MedSubtype1', array(
             'local' => 'med_subtype1_id',
             'foreign' => 'med_subtype1_id'));

        $this->hasOne('MedSubtype2', array(
             'local' => 'med_subtype2_id',
             'foreign' => 'med_subtype2_id'));

        $this->hasMany('MedBaseId', array(
             'local' => 'med_type_id',
             'foreign' => 'med_type_id'));
    }
}