<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IntEnzym', 'doctrine');

/**
 * BaseIntEnzym
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $int_enzym_id
 * @property string $name
 * @property Doctrine_Collection $IntDrug
 * @property Doctrine_Collection $IntMetabolism
 * 
 * @method integer             getIntEnzymId()    Returns the current record's "int_enzym_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method Doctrine_Collection getIntDrug()       Returns the current record's "IntDrug" collection
 * @method Doctrine_Collection getIntMetabolism() Returns the current record's "IntMetabolism" collection
 * @method IntEnzym            setIntEnzymId()    Sets the current record's "int_enzym_id" value
 * @method IntEnzym            setName()          Sets the current record's "name" value
 * @method IntEnzym            setIntDrug()       Sets the current record's "IntDrug" collection
 * @method IntEnzym            setIntMetabolism() Sets the current record's "IntMetabolism" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIntEnzym extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('int_enzym');
        $this->hasColumn('int_enzym_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('IntDrug', array(
             'local' => 'int_enzym_id',
             'foreign' => 'int_enzym_id'));

        $this->hasMany('IntMetabolism', array(
             'local' => 'int_enzym_id',
             'foreign' => 'enzym_group_id'));
    }
}