<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MedSubtype1', 'doctrine');

/**
 * BaseMedSubtype1
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $med_subtype1_id
 * @property string $name
 * @property Doctrine_Collection $MedType
 * 
 * @method integer             getMedSubtype1Id()   Returns the current record's "med_subtype1_id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method Doctrine_Collection getMedType()         Returns the current record's "MedType" collection
 * @method MedSubtype1         setMedSubtype1Id()   Sets the current record's "med_subtype1_id" value
 * @method MedSubtype1         setName()            Sets the current record's "name" value
 * @method MedSubtype1         setMedType()         Sets the current record's "MedType" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedSubtype1 extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('med_subtype1');
        $this->hasColumn('med_subtype1_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MedType', array(
             'local' => 'med_subtype1_id',
             'foreign' => 'med_subtype1_id'));
    }
}