<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MedMagisterForm', 'doctrine');

/**
 * BaseMedMagisterForm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $med_magister_form_id
 * @property string $naam
 * @property Doctrine_Collection $MedForm
 * 
 * @method integer             getMedMagisterFormId()    Returns the current record's "med_magister_form_id" value
 * @method string              getNaam()                 Returns the current record's "naam" value
 * @method Doctrine_Collection getMedForm()              Returns the current record's "MedForm" collection
 * @method MedMagisterForm     setMedMagisterFormId()    Sets the current record's "med_magister_form_id" value
 * @method MedMagisterForm     setNaam()                 Sets the current record's "naam" value
 * @method MedMagisterForm     setMedForm()              Sets the current record's "MedForm" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMedMagisterForm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('med_magister_form');
        $this->hasColumn('med_magister_form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('naam', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('MedForm', array(
             'local' => 'med_magister_form_id',
             'foreign' => 'med_magister_form_id'));
    }
}