<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PatientMedicijn', 'doctrine');

/**
 * BasePatientMedicijn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $patient_id
 * @property integer $medicijn_id
 * @property integer $aantal
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method integer         getPatientId()   Returns the current record's "patient_id" value
 * @method integer         getMedicijnId()  Returns the current record's "medicijn_id" value
 * @method integer         getAantal()      Returns the current record's "aantal" value
 * @method timestamp       getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()   Returns the current record's "updated_at" value
 * @method PatientMedicijn setId()          Sets the current record's "id" value
 * @method PatientMedicijn setPatientId()   Sets the current record's "patient_id" value
 * @method PatientMedicijn setMedicijnId()  Sets the current record's "medicijn_id" value
 * @method PatientMedicijn setAantal()      Sets the current record's "aantal" value
 * @method PatientMedicijn setCreatedAt()   Sets the current record's "created_at" value
 * @method PatientMedicijn setUpdatedAt()   Sets the current record's "updated_at" value
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatientMedicijn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patient_medicijn');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('patient_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('medicijn_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('aantal', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}