<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AdRole', 'doctrine');

/**
 * BaseAdRole
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $role_id
 * @property string $name
 * @property Doctrine_Collection $AdUser
 * 
 * @method integer             getRoleId()  Returns the current record's "role_id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getAdUser()  Returns the current record's "AdUser" collection
 * @method AdRole              setRoleId()  Sets the current record's "role_id" value
 * @method AdRole              setName()    Sets the current record's "name" value
 * @method AdRole              setAdUser()  Sets the current record's "AdUser" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAdRole extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ad_role');
        $this->hasColumn('role_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AdUser', array(
             'local' => 'role_id',
             'foreign' => 'ad_role_id'));
    }
}