<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IntEnzymType', 'doctrine');

/**
 * BaseIntEnzymType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $med_enzym_types_id
 * @property string $name
 * @property Doctrine_Collection $IntEnzym
 * 
 * @method integer             getMedEnzymTypesId()    Returns the current record's "med_enzym_types_id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method Doctrine_Collection getIntEnzym()           Returns the current record's "IntEnzym" collection
 * @method IntEnzymType        setMedEnzymTypesId()    Sets the current record's "med_enzym_types_id" value
 * @method IntEnzymType        setName()               Sets the current record's "name" value
 * @method IntEnzymType        setIntEnzym()           Sets the current record's "IntEnzym" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIntEnzymType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('int_enzym_type');
        $this->hasColumn('med_enzym_types_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 45,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('IntEnzym', array(
             'local' => 'med_enzym_types_id',
             'foreign' => 'int_enzym_type_id'));
    }
}