<?php

/**
 * BasePatientMedicijn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $patient_id
 * @property integer $Medicijn_id
 * @property integer $aantal
 * @property Doctrine_Collection $PatientMedicijn
 * 
 * @method integer             getPatientId()       Returns the current record's "patient_id" value
 * @method integer             getMedicijnId()      Returns the current record's "Medicijn_id" value
 * @method integer             getAantal()          Returns the current record's "aantal" value
 * @method Doctrine_Collection getPatientMedicijn() Returns the current record's "PatientMedicijn" collection
 * @method PatientMedicijn     setPatientId()       Sets the current record's "patient_id" value
 * @method PatientMedicijn     setMedicijnId()      Sets the current record's "Medicijn_id" value
 * @method PatientMedicijn     setAantal()          Sets the current record's "aantal" value
 * @method PatientMedicijn     setPatientMedicijn() Sets the current record's "PatientMedicijn" collection
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatientMedicijn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patient_medicijn');
        $this->hasColumn('patient_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('Medicijn_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('aantal', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Patient as PatientMedicijn', array(
             'local' => 'patient_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}