<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('IntMetabolism', 'doctrine');

/**
 * BaseIntMetabolism
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $int_metabolism_id
 * @property integer $med_form_id
 * @property integer $enzym_group_id
 * @property enum $interaction_type
 * @property MedForm $MedForm
 * @property IntEnzym $IntEnzym
 * 
 * @method integer       getIntMetabolismId()   Returns the current record's "int_metabolism_id" value
 * @method integer       getMedFormId()         Returns the current record's "med_form_id" value
 * @method integer       getEnzymGroupId()      Returns the current record's "enzym_group_id" value
 * @method enum          getInteractionType()   Returns the current record's "interaction_type" value
 * @method MedForm       getMedForm()           Returns the current record's "MedForm" value
 * @method IntEnzym      getIntEnzym()          Returns the current record's "IntEnzym" value
 * @method IntMetabolism setIntMetabolismId()   Sets the current record's "int_metabolism_id" value
 * @method IntMetabolism setMedFormId()         Sets the current record's "med_form_id" value
 * @method IntMetabolism setEnzymGroupId()      Sets the current record's "enzym_group_id" value
 * @method IntMetabolism setInteractionType()   Sets the current record's "interaction_type" value
 * @method IntMetabolism setMedForm()           Sets the current record's "MedForm" value
 * @method IntMetabolism setIntEnzym()          Sets the current record's "IntEnzym" value
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseIntMetabolism extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('int_metabolism');
        $this->hasColumn('int_metabolism_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('med_form_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('enzym_group_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('interaction_type', 'enum', 10, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'metabolism',
              1 => 'inhibitor',
              2 => 'inducer',
             ),
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MedForm', array(
             'local' => 'med_form_id',
             'foreign' => 'med_form_id'));

        $this->hasOne('IntEnzym', array(
             'local' => 'enzym_group_id',
             'foreign' => 'enzym_id'));
    }
}