<?php

/**
 * BasePatient
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $Naam
 * @property string $Voornaam
 * @property boolean $Geslacht
 * @property string $Geboortedatum
 * @property string $Medicatiescheme
 * @property string $Opmerkingen
 * @property string $Voorgeschiedenis
 * @property PatientMedicijn $PatientMedicijn
 * 
 * @method string          getNaam()             Returns the current record's "Naam" value
 * @method string          getVoornaam()         Returns the current record's "Voornaam" value
 * @method boolean         getGeslacht()         Returns the current record's "Geslacht" value
 * @method string          getGeboortedatum()    Returns the current record's "Geboortedatum" value
 * @method string          getMedicatiescheme()  Returns the current record's "Medicatiescheme" value
 * @method string          getOpmerkingen()      Returns the current record's "Opmerkingen" value
 * @method string          getVoorgeschiedenis() Returns the current record's "Voorgeschiedenis" value
 * @method PatientMedicijn getPatientMedicijn()  Returns the current record's "PatientMedicijn" value
 * @method Patient         setNaam()             Sets the current record's "Naam" value
 * @method Patient         setVoornaam()         Sets the current record's "Voornaam" value
 * @method Patient         setGeslacht()         Sets the current record's "Geslacht" value
 * @method Patient         setGeboortedatum()    Sets the current record's "Geboortedatum" value
 * @method Patient         setMedicatiescheme()  Sets the current record's "Medicatiescheme" value
 * @method Patient         setOpmerkingen()      Sets the current record's "Opmerkingen" value
 * @method Patient         setVoorgeschiedenis() Sets the current record's "Voorgeschiedenis" value
 * @method Patient         setPatientMedicijn()  Sets the current record's "PatientMedicijn" value
 * 
 * @package    GuizMed
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePatient extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('patient');
        $this->hasColumn('Naam', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('Voornaam', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('Geslacht', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('Geboortedatum', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('Medicatiescheme', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('Opmerkingen', 'string', 4000, array(
             'type' => 'string',
             'length' => 4000,
             ));
        $this->hasColumn('Voorgeschiedenis', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PatientMedicijn', array(
             'local' => 'id',
             'foreign' => 'patient_id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}