<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/21 08:47:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=guizmed',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
