<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/04/21 08:49:48
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'C:/wamp/www/guizmed/GuizMed/lib/Vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'basemedicijnformfilter' => 'C:/wamp/www/guizmed/GuizMed/lib/filter/doctrine/base/BaseMedicijnFormFilter.class.php',
  'basepatientformfilter' => 'C:/wamp/www/guizmed/GuizMed/lib/filter/doctrine/base/BasePatientFormFilter.class.php',
  'basepatientmedicijnformfilter' => 'C:/wamp/www/guizmed/GuizMed/lib/filter/doctrine/base/BasePatientMedicijnFormFilter.class.php',
  'baseformfilterdoctrine' => 'C:/wamp/www/guizmed/GuizMed/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'medicijnformfilter' => 'C:/wamp/www/guizmed/GuizMed/lib/filter/doctrine/MedicijnFormFilter.class.php',
  'patientformfilter' => 'C:/wamp/www/guizmed/GuizMed/lib/filter/doctrine/PatientFormFilter.class.php',
  'patientmedicijnformfilter' => 'C:/wamp/www/guizmed/GuizMed/lib/filter/doctrine/PatientMedicijnFormFilter.class.php',
  'baseform' => 'C:/wamp/www/guizmed/GuizMed/lib/form/BaseForm.class.php',
  'basemedicijnform' => 'C:/wamp/www/guizmed/GuizMed/lib/form/doctrine/base/BaseMedicijnForm.class.php',
  'basepatientform' => 'C:/wamp/www/guizmed/GuizMed/lib/form/doctrine/base/BasePatientForm.class.php',
  'basepatientmedicijnform' => 'C:/wamp/www/guizmed/GuizMed/lib/form/doctrine/base/BasePatientMedicijnForm.class.php',
  'baseformdoctrine' => 'C:/wamp/www/guizmed/GuizMed/lib/form/doctrine/BaseFormDoctrine.class.php',
  'medicijnform' => 'C:/wamp/www/guizmed/GuizMed/lib/form/doctrine/MedicijnForm.class.php',
  'patientform' => 'C:/wamp/www/guizmed/GuizMed/lib/form/doctrine/PatientForm.class.php',
  'patientmedicijnform' => 'C:/wamp/www/guizmed/GuizMed/lib/form/doctrine/PatientMedicijnForm.class.php',

  // project_model
  'basemedicijn' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/base/BaseMedicijn.class.php',
  'basepatient' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/base/BasePatient.class.php',
  'basepatientmedicijn' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/base/BasePatientMedicijn.class.php',
  'medicijn' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/Medicijn.class.php',
  'medicijntable' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/MedicijnTable.class.php',
  'patient' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/Patient.class.php',
  'patientmedicijn' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/PatientMedicijn.class.php',
  'patientmedicijntable' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/PatientMedicijnTable.class.php',
  'patienttable' => 'C:/wamp/www/guizmed/GuizMed/lib/model/doctrine/PatientTable.class.php',

  // application
  'myuser' => 'C:/wamp/www/guizmed/GuizMed/apps/frontend/lib/myUser.class.php',

  // modules
);
