<?php

/**
 * AdFunctionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdFunctionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdFunctionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdFunction');
    }
}