<?php

/**
 * AdLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdLog');
    }
}