<?php

/**
 * AdPatientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdPatientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdPatientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdPatient');
    }
}