<?php

/**
 * AdRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdRoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdRole');
    }
}