<?php

/**
 * AdUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AdUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AdUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AdUser');
    }
}