<?php

/**
 * IntEnzymTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntEnzymTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntEnzymTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntEnzym');
    }
}