<?php

/**
 * IntEnzymBrandTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntEnzymBrandTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntEnzymBrandTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntEnzymBrand');
    }
}