<?php

/**
 * IntEnzymSubgroupTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntEnzymSubgroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntEnzymSubgroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntEnzymSubgroup');
    }
}