<?php

/**
 * IntEnzymTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntEnzymTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntEnzymTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntEnzymType');
    }
}