<?php

/**
 * IntInteractionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntInteractionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntInteractionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntInteraction');
    }
}