<?php

/**
 * IntMetabolismTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class IntMetabolismTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object IntMetabolismTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('IntMetabolism');
    }
}