<?php

/**
 * MedBnfMedicineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedBnfMedicineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedBnfMedicineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedBnfMedicine');
    }
}