<?php

/**
 * MedBnfPercentageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedBnfPercentageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedBnfPercentageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedBnfPercentage');
    }
}