<?php

/**
 * MedChemBondingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedChemBondingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedChemBondingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedChemBonding');
    }
}