<?php

/**
 * MedFormBondingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedFormBondingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedFormBondingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedFormBonding');
    }
}