<?php

/**
 * MedicijnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedicijnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedicijnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Medicijn');
    }
}