<?php

/**
 * MedKiValTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedKiValTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedKiValTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedKiVal');
    }
}