<?php

/**
 * MedMagisterFormTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedMagisterFormTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedMagisterFormTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedMagisterForm');
    }
}