<?php

/**
 * MedSubtype2Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedSubtype2Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedSubtype2Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedSubtype2');
    }
}