<?php

/**
 * MedSubtype1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedSubtype1Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedSubtype1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedSubtype1');
    }
}