<?php

/**
 * MedTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MedTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MedTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MedType');
    }
}