<?php

/**
 * PatientMedicijnTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PatientMedicijnTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PatientMedicijnTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PatientMedicijn');
    }
}