<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/04/21 11:17:30

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=GuizMed',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
